clear all
close all
clc
load('KangSpline.mat')
DataIn = Data;

%% Please Select parallel or serial bisecting method, 1 for parallel and 0 for serial
ParallelFlag = 1;
%% Parallel bisecting
if ParallelFlag
    Degree = 3;
    NumOfPieceStart = 10;
    CtrlError = 0.000001;
    MinAngle = 0.002;
    MaxSmooth = -1;
    N0ScanForDiscontinuosCase = 10;
    GaussNewtonLoopTime = 10;
    ScanKnot = 0;
    tic
    [BSpline,MaxError,FittedData] = BSplineCurveFittingParallelBisection...
    (DataIn,Degree,CtrlError,NumOfPieceStart,MinAngle,MaxSmooth,N0ScanForDiscontinuosCase,...
    GaussNewtonLoopTime,ScanKnot);
    toc
    
else
%% Serial bisecting    
    Degree = 3;
    CtrlError = 0.000001;
    MinAngle = 0.002;
    MaxSmooth = -1;
    ScanKnot = 0;
    N0ScanForDiscontinuosCase = 10;
    GaussNewtonLoopTime = 10;    
    tic
    [BSpline,MaxError,FittedData] = BSplineCurveFittingSerialBisection...
    (DataIn,Degree,CtrlError,MinAngle,MaxSmooth,N0ScanForDiscontinuosCase,...
    GaussNewtonLoopTime,ScanKnot);
    toc
end
%% Show the result and plot figure    
format short
A = BSpline.knot(5:end-4);
% Calculate knot residual error
A0 = [0.0439,0.0653,0.2293,0.2367,0.4821,0.4907,0.5408,0.5408,0.6209,0.7051,0.9407];
Em = A-A0;
Em'
max(abs(Em))
% plot(DataIn(:,1),MaxError)
%% plot B-Spline 
xlocation = 0;
ylocation = 0;
width = 17;
height = 6;
figure('Units','centimeters',...
'Position',[xlocation ylocation width height],...
'PaperPositionMode','auto');
subplot(1,2,1);
plot(FittedData(:,1),FittedData(:,2),'-k','LineWidth',0.5)
hold on
Knotplot =zeros(size(BSpline.knot))-18;
Knotplot(12)=-15;
for ii = 2:(Degree + 1)
    Knotplot(ii)=Knotplot(ii-1)+3;
    Knotplot(end-ii+1)=Knotplot(end-ii+2)+3;
end
plot(BSpline.knot,Knotplot,'^','MarkerFaceColor',[0 0 0],...
    'MarkerEdgeColor',[0 0 0],...
    'MarkerSize',2);
title('B-Spline function',...
'FontUnits','points',...
'FontWeight','normal',...
'FontSize',7,...
'FontName','Times')
xlabel('a) B-Spline function',...
'FontUnits','points',...
'FontWeight','normal',...
'FontSize',7,...
'FontName','Times')
set(gca,...
'Units','normalized',...
'Position',[0.05 0.2 0.42 0.7],...
'XLim',[0,1],...
'YLim',[-20,90],...
'FontUnits','points',...
'FontWeight','normal',...
'FontSize',7,...
'FontName','Times')
% print -depsc -r1200 'BSpline_Kang.eps'
%print -djpeg -r720 'BSpline_Kang.jpg'
%% plot B-Spline error
% xlocation = 0;
% ylocation = 0;
% width = 8;
% height = 5;
% figure('Units','centimeters',...
% 'Position',[xlocation ylocation width height],...
% 'PaperPositionMode','auto');
subplot(1,2,2);
plot(FittedData(:,1),MaxError,'-k','LineWidth',0.5)

title('Fitting Error',...
'FontUnits','points',...
'FontWeight','normal',...
'FontSize',7,...
'FontName','Times')
xlabel('b) Fitting Error',...
'FontUnits','points',...
'FontWeight','normal',...
'FontSize',7,...
'FontName','Times')
set(gca,...
'Units','normalized',...
'Position',[0.55 0.2 0.42 0.7],...
'XLim',[0,1],...
'YLim',[0,6e-7],...
'FontUnits','points',...
'FontWeight','normal',...
'FontSize',7,...
'FontName','Times')
% print -depsc -r1200 'BSpline_Kang_Error.eps'
%print -djpeg -r1200 'BSpline_Kang_Error.jpg'
print -dtiff -r600 'Fig8.tif'

